# Summary

Search the Bedrock Knowledge base

In [1]:
import os, sys
import pandas as pd
import re
import json
import time

# AWS Python
import boto3

utils_path = "/Users/stephengodfrey/Documents/Workbench/Numantic/utilities/.."
sys.path.insert(0, utils_path)
from utilities.osa_tools.authentication import ApiAuthentication

api_configs = ApiAuthentication(client="Numantic")

## Construct a AWS Bedrock Retrieval and Generate class object

In [2]:
class BedrockKBRetriever:
    """
    Class to demonstrate AWS Bedrock Knowledge Base retrieve and retrieve and generate results.
    """

    def __init__(self,
                 aws_profile: str,
                 aws_region: str,
                 kb_id: str):

        self.aws_profile = aws_profile
        self.aws_region = aws_region
        self.kb_id = kb_id

        # Retrieval configuration
        self.num_srch_res = 5
        self.s3_bucket = "ashoka-search-tests"
        self.s3_doc_loc = "s3://{}/".format(self.s3_bucket)

        # Retrieval and Generation configuration
        self.aws_account_id = os.environ["AWS_ACCOUNT_ID"]
        # self.inference_model = "amazon.nova-lite-v1:0" #?
        # self.inference_model = "anthropic.claude-sonnet-4-6" # Requires Anthropic request form
        # self.inference_model = "google.gemma-3-4b-it" # Not available
        self.inference_model = "meta.llama4-scout-17b-instruct-v1:0"
        self.model_arn = "arn:aws:bedrock:{}:{}:inference-profile/us.{}".format(self.aws_region,
                                                                                self.aws_account_id,
                                                                                self.inference_model)
        self.search_sleep_time = 5 # pause time between queries
        self.ai_sleep_time = 5 # pause time between queries

        # Outputs
        self.df_ret_res = pd.DataFrame()
        self.df_query_finds = pd.DataFrame()
        self.df_rag_res = pd.DataFrame()
        self.bedrock_models = pd.DataFrame() # AWS foundation models - requires get_bedrock_foundational_models method

        # Establish an AWS client
        self.set_aws_client()

    def set_aws_client(self):
        """
        Create a AWS client
        :return:
        """

        # Initialize Bedrock Agent Runtime client for querying
        session = boto3.Session(profile_name=self.aws_profile)

        # Bedrock client
        self.br_rt = session.client('bedrock-agent-runtime',
                                    region_name=self.aws_region)

        # S3 client
        self.s3 = session.client('s3',
                                 region_name=self.aws_region)

    def get_bedrock_foundational_models(self):
        """
        Get a list of foundation models available through Bedrock
        :return:
        """

        # Initialize a bedrock client
        session = boto3.Session(profile_name=self.aws_profile)
        self.br = session.client('bedrock', region_name=self.aws_region)

        response = self.br.list_foundation_models()
        self.response_models = response

        models_rows = []
        for model in response['modelSummaries']:
            models_rows.append(dict(model_name=model['modelName'],
                                    model_id=model['modelId'],
                                    model_provider=model['providerName'],
                                    input_modalities=model['inputModalities'],
                                    output_modalities=model['outputModalities'],
                                    infer_types=model['inferenceTypesSupported'],
                                    model_lifecycle=model['modelLifecycle']
                                    )
                               )

        self.bedrock_models = pd.DataFrame(data=models_rows)
        self.bedrock_models = self.bedrock_models.sort_values(by="model_provider")
        self.bedrock_models = self.bedrock_models.reset_index(drop=True)

    def retrieve_query_results(self,
                               queries: list,
                               source_types: list = []):
        """
        Return AWS Bedrock search results for a list of queries. Filtering before searching can be
        applied by passing source type values in the source_types input parameter.
        :return:
        """

        # Set retrieval configurations
        if len(source_types) == 0:
            ret_config = {'vectorSearchConfiguration': {
                                                        'numberOfResults': self.num_srch_res
                                                        }
                         }

        if len(source_types) > 0:
            ret_config = {'vectorSearchConfiguration': {
                                                        'numberOfResults': self.num_srch_res,
                                                        'filter': {
                                                            'in': {
                                                                'key': 'source_type',
                                                                'value': source_types
                                                            }
                                                        }
                                                        }
                         }

        search_results = []
        for query in queries:

            # Set retrieval configurations
            ret_query_param = {'text': query
                               }

            response = self.br_rt.retrieve(knowledgeBaseId=self.kb_id,
                                           retrievalQuery=ret_query_param,
                                           retrievalConfiguration=ret_config
                                           )

            for result in response["retrievalResults"]:

                # Get list of passages
                regex_pattern = r"Passage\s#(\d+)"

                passages = re.findall(regex_pattern, result['content']['text'], flags=re.DOTALL)

                # Clean up whitespace from the results
                passages = [p.strip() for p in passages]

                # Get metadata
                s3_loc=result['location']['s3Location']['uri']
                doc_name = s3_loc.replace(self.s3_doc_loc, "")
                key = "{}.metadata.json".format(doc_name)

                # Read the file from S3
                response_docread = self.s3.get_object(Bucket=self.s3_bucket,
                                                      Key=key)
                content = response_docread['Body'].read().decode('utf-8')

                # Parse JSON into dictionary
                metadata_dict = json.loads(content)
                source_type = metadata_dict["metadataAttributes"]["source_type"]

                res_dict = dict(query=query,
                                search_res=result['content']['text'],
                                passages=passages,
                                score=result['score'],
                                s3_loc=result['location']['s3Location']['uri'],
                                source_type=source_type,
                                doc_metadata=metadata_dict
                                )

                search_results.append(res_dict)

                time.sleep(self.search_sleep_time)

        # Put the detailed retrieval results into a dataframe
        self.df_ret_res = pd.DataFrame(search_results)

        # Aggregate results by query
        self.aggregate_retrieval_results()

    def aggregate_retrieval_results(self):
        """
        Aggregate retrieval results by query
        :param queries:
        :return:
        """

        q_rows = []
        for query in self.df_ret_res["query"].unique():

            mask = self.df_ret_res["query"] == query

            doc_value_cnts = self.df_ret_res[mask]["s3_loc"].value_counts()

            # Get passages
            pass_dict = {}
            for idx in self.df_ret_res[mask].index:
                doc_filename = self.df_ret_res.loc[idx, "s3_loc"].replace(self.s3_doc_loc, "")

                if doc_filename in pass_dict:
                    pass_dict[doc_filename] = pass_dict[doc_filename] + self.df_ret_res.loc[idx, "passages"]
                else:
                    pass_dict[doc_filename] = self.df_ret_res.loc[idx, "passages"]

            for df in pass_dict:
                pass_dict[df] = list(set(pass_dict[df]))
                pass_dict[df].sort()

            doc_dict = {}
            for s3_loc_idx in doc_value_cnts.index:
                ikey = s3_loc_idx.replace(self.s3_doc_loc, "")
                doc_dict[ikey] = int(doc_value_cnts[s3_loc_idx])

            doc_count = len(doc_dict)

            max_score = self.df_ret_res[mask]["score"].max()

            source_types = self.df_ret_res[mask]["source_type"].unique().tolist()

            q_rows.append(dict(query=query,
                               doc_count=doc_count,
                               max_score=max_score,
                               doc_scores=doc_dict,
                               passages=pass_dict,
                               source_types=source_types
                               )
                          )

        self.df_query_finds = pd.DataFrame(q_rows)

    def retrieve_and_generate_results(self,
                                      queries: list,
                                      source_types: list = []):
        """
        Retrieve AWS Bedrock search results and for a list of queries and generate AI responses summarizing the findings. Filtering before searching can be
        applied by passing source type values in the source_types input parameter.
        :return:
        """

        # Set retrieval configurations
        if len(source_types) == 0:
            ret_gen_config = {'type': 'KNOWLEDGE_BASE',
                              'knowledgeBaseConfiguration': {'knowledgeBaseId': self.kb_id,
                                                             'modelArn': self.model_arn
                                                             }
                              }

        if len(source_types) > 0:
              ret_gen_config = {'type': 'KNOWLEDGE_BASE',
                              'knowledgeBaseConfiguration': {'knowledgeBaseId': self.kb_id,
                                                             'modelArn': self.model_arn,
                                                             'retrievalConfiguration': {
                                                                'vectorSearchConfiguration': {
                                                                    'numberOfResults': self.num_srch_res,
                                                                    'filter': {
                                                                        'in': {
                                                                            'key': 'source_type',
                                                                            'value':  source_types
                                                                        }
                                                                    }
                                                                }
                                                             }
                                                             }
                                }

        search_results = []
        for query in queries:

            rag_response = self.br_rt.retrieve_and_generate(input={'text': query},
                                                            retrieveAndGenerateConfiguration=ret_gen_config
                                                            )

            rag_answer = rag_response['output']['text']

            citations_list = []
            for citation in rag_response['citations']:
                for reference in citation['retrievedReferences']:
                    if 'location' in reference:
                        if 's3Location' in reference['location']:
                            citations_list.append(reference['location']['s3Location']['uri'])

            search_results.append(dict(query=query,
                                       rag_answer=rag_answer,
                                       rag_citations=citations_list)
                                    )

            time.sleep(self.ai_sleep_time)

        self.df_rag_res = pd.DataFrame(search_results)

## Read test data

In [3]:
input_data_path = "../data/rag_eval_dataset"
docs_filename = "documents.csv"
multi_pas_qs = "multi_passage_answer_questions.csv"
no_answer_qs = "no_answer_questions.csv"
single_pas_answer_qs = "single_passage_answer_questions.csv"

df_docs = pd.read_csv(filepath_or_buffer=os.path.join(input_data_path, docs_filename))
df_mpqs = pd.read_csv(filepath_or_buffer=os.path.join(input_data_path, multi_pas_qs))
df_noaqs = pd.read_csv(filepath_or_buffer=os.path.join(input_data_path, no_answer_qs))
df_spqs = pd.read_csv(filepath_or_buffer=os.path.join(input_data_path, single_pas_answer_qs))

In [5]:
# df_docs

## Get available foundational models

In [34]:
# Set up some parameters
aws_profile = "ns-admin"
aws_region = 'us-east-2'
kb_id = "DBSECKYXJV"

# Set up retriever object
srch_analyzer = BedrockKBRetriever(aws_profile=aws_profile,
                                   aws_region=aws_region,
                                   kb_id=kb_id)

# Set queries
srch_analyzer.get_bedrock_foundational_models()

In [36]:
srch_analyzer.bedrock_models.loc[[20]].T
srch_analyzer.bedrock_models.loc[[31]].T
# srch_analyzer.bedrock_models

# srch_analyzer.response_models

                                                                  31
model_name                                Llama 4 Scout 17B Instruct
model_id                         meta.llama4-scout-17b-instruct-v1:0
model_provider                                                  Meta
input_modalities                                       [TEXT, IMAGE]
output_modalities                                             [TEXT]
infer_types                                      [INFERENCE_PROFILE]
model_lifecycle    {'status': 'ACTIVE', 'startOfLifeTime': 2025-0...

## Retrieve Search Results

In [6]:
# Set up some parameters
aws_profile = "ns-admin"
aws_region = 'us-east-2'
kb_id = "DBSECKYXJV"

# Set up retriever object
srch_analyzer = BedrockKBRetriever(aws_profile=aws_profile,
                                   aws_region=aws_region,
                                   kb_id=kb_id)

# Set queries
queries = df_spqs["question"].tolist()

# Search documents for text related to queries without filtering
srch_analyzer.retrieve_query_results(queries=queries)

# Search documents for text related to queries with filtering
# srch_analyzer.retrieve_query_results(queries=queries,
#                                      source_types=["gaming"])

In [11]:

# srch_analyzer.df_ret_res
srch_analyzer.df_query_finds

,query,doc_count,max_score,doc_scores,passages,source_types
0,What do keybullet kin drop?,1,0.637887,{'doc_0.txt': 5},"{'doc_0.txt': ['1', '2', '26', '27', '28', '29...",[gaming]
1,What kind of gun does the bandana bullet kin use?,1,0.591255,{'doc_0.txt': 5},"{'doc_0.txt': ['1', '10', '11', '12', '13', '1...",[gaming]
2,What do the giants look like?,2,0.371861,"{'doc_15.txt': 3, 'doc_0.txt': 2}","{'doc_15.txt': [], 'doc_0.txt': ['10', '11', '...","[entertainment, gaming]"
3,What happens on day 2?,3,0.381578,"{'doc_16.txt': 2, 'doc_18.txt': 2, 'doc_9.txt'...","{'doc_16.txt': [], 'doc_18.txt': ['19', '20', ...","[gaming, entertainment]"
4,What were the requirements for the project?,5,0.377493,"{'doc_6.txt': 1, 'doc_2.txt': 1, 'doc_5.txt': ...","{'doc_6.txt': ['57', '58', '59', '60', '61'], ...","[government, data_science, entertainment, gaming]"
5,What data did was used to test the prototype?,1,0.440606,{'doc_2.txt': 5},"{'doc_2.txt': ['17', '18', '19', '20', '21', '...",[data_science]
6,How do the data storage options compare?,4,0.420020,"{'doc_2.txt': 2, 'doc_3.txt': 1, 'doc_16.txt':...","{'doc_3.txt': ['36'], 'doc_16.txt': [], 'doc_2...","[data_science, gaming]"
7,When was UTF-8 support added for European lang...,3,0.384851,"{'doc_3.txt': 2, 'doc_16.txt': 2, 'doc_11.txt'...","{'doc_11.txt': ['75', '76', '77'], 'doc_3.txt'...","[data_science, gaming]"
8,How do I make a button?,1,0.422285,{'doc_4.txt': 5},"{'doc_4.txt': ['100', '101', '102', '103', '50...",[recipes]
9,When might I use caching?,3,0.455322,"{'doc_4.txt': 2, 'doc_19.txt': 2, 'doc_11.txt'...","{'doc_4.txt': ['1', '103', '104', '105', '106'...","[recipes, data_science]"
10,What are the key topics of this article?,3,0.371317,"{'doc_19.txt': 3, 'doc_8.txt': 1, 'doc_18.txt'...","{'doc_8.txt': ['12', '13'], 'doc_19.txt': [], ...","[recipes, data_science, entertainment]"
11,Do I have to do something all by myself to be ...,2,0.397335,"{'doc_5.txt': 4, 'doc_13.txt': 1}","{'doc_5.txt': ['1', '19', '2', '20', '21', '22...",[data_science]
12,What kinds of models would need to be official...,2,0.405289,"{'doc_6.txt': 4, 'doc_3.txt': 1}","{'doc_6.txt': ['21', '22', '23', '24', '25', '...","[government, data_science]"
13,"What kinds of AI carry ""systematic risks""?",1,0.612117,{'doc_6.txt': 5},"{'doc_6.txt': ['14', '15', '16', '17', '18', '...",[government]
14,Which quest does the emperor give the player?,1,0.553820,{'doc_7.txt': 5},"{'doc_7.txt': ['1', '2', '27', '28', '29', '3'...",[gaming]
15,Who ambushes the party at Wyrm's lookout?,3,0.406581,"{'doc_17.txt': 2, 'doc_1.txt': 2, 'doc_7.txt': 1}","{'doc_7.txt': ['16', '17'], 'doc_17.txt': ['10...",[gaming]
16,What did I drink at the pintxo bars?,2,0.511985,"{'doc_8.txt': 4, 'doc_14.txt': 1}","{'doc_8.txt': ['1', '10', '11', '13', '14', '1...","[recipes, entertainment]"
17,Which part of the trip did I like the most?,1,0.412948,{'doc_8.txt': 5},"{'doc_8.txt': ['1', '18', '19', '2', '20', '21...",[recipes]
18,What is the meaning behind the infrared scenes?,3,0.521365,"{'doc_9.txt': 3, 'doc_7.txt': 1, 'doc_18.txt': 1}","{'doc_9.txt': ['13', '14', '8'], 'doc_7.txt': ...","[entertainment, gaming]"
19,How do the people who commit atrocious acts an...,4,0.380423,"{'doc_6.txt': 2, 'doc_18.txt': 1, 'doc_13.txt'...","{'doc_6.txt': ['10', '11', '12', '13', '14', '...","[government, entertainment, data_science]"
20,What is the policy on Tai Chi?,2,0.414442,"{'doc_10.txt': 4, 'doc_13.txt': 1}","{'doc_10.txt': ['17', '18', '19', '20', '21', ...","[entertainment, data_science]"
21,What is the proposed change for the British mu...,1,0.424493,{'doc_10.txt': 5},"{'doc_10.txt': ['1', '10', '11', '12', '13', '...",[entertainment]
22,How much faster is the Tesla A100 compared to ...,1,0.658901,{'doc_11.txt': 5},"{'doc_11.txt': ['32', '33', '34', '42', '43', ...",[data_science]
23,For what work did I receive criticism for my r...,2,0.396787,"{'doc_5.txt': 4, 'doc_6.txt': 1}","{'doc_5.txt': ['19', '20', '21', '22', '23', '...","[data_science, government]"
24,How does function exporting differ between Gle...,1,0.577366,{'doc_12.txt': 5},"{'doc_12.txt': ['1', '10', '11', '12', '18', '...",[data_science]
25,What is the syntax for pipe,3,0.376836,"{'doc_12.txt': 2, 'doc_15.txt': 2, 'doc_4.txt'...","{'doc_12.txt': ['41', '42', '43', '44', '45', ...","[data_science, recipes, entertainment]"
26,Why are the top-right values in the raw attent...,1,0.476450,{'doc_13.txt': 5},"{'doc_13.txt': ['40', '41', '42', '43', '44', ...",[data_science]
27,How can I freeze a variable during training in...,1,0.460734,{'doc_13.txt': 5},"{'doc_13.txt': ['100', '101', '102', '103', '1...",[data_science]
28,How is the narrator related to Perry,1,0.572627,{'doc_14.txt': 5},"{'doc_14.txt': ['1', '10', '2', '26', '27', '2...",[entertainment]
29,How long has the narrator been sober for?,1,0.426491,{'doc_14.txt': 5},"{'doc_14.txt': ['10', '100', '101', '11', '12'...",[entertainment]
30,What is the name of the space station?,1,0.407861,{'doc_15.txt': 5},"{'doc_15.txt': ['18', '19', '20', '21', '60', ...",[entertainment]
31,What languages do the people of Pacifico del R...,4,0.462322,"{'doc_15.txt': 2, 'doc_16.txt': 1, 'doc_8.txt'...","{'doc_15.txt': ['12', '13', '14', '15'], 'doc_...","[entertainment, gaming, recipes, data_science]"
32,In which patch was pet adoption added?,1,0.424155,{'doc_16.txt': 5},{'doc_16.txt': []},[gaming]
33,When did mushroom trees stop dropping wood?,1,0.473022,{'doc_16.txt': 5},{'doc_16.txt': []},[gaming]
34,Where was Alan Wake 2 officially announced?,1,0.799156,{'doc_17.txt': 5},"{'doc_17.txt': ['1', '2', '27', '28', '3', '35...",[gaming]
35,When is this game set?,3,0.398366,"{'doc_17.txt': 3, 'doc_15.txt': 1, 'doc_16.txt...","{'doc_17.txt': ['23', '24', '25', '6', '7', '8...","[gaming, entertainment]"
36,Who wrote 'Divine Rivals'?,1,0.393278,{'doc_18.txt': 5},"{'doc_18.txt': ['26', '27', '28', '30', '31', ...",[entertainment]
37,Who was resurrected with a group of other murd...,2,0.407566,"{'doc_17.txt': 3, 'doc_18.txt': 2}","{'doc_18.txt': ['35', '36', '37'], 'doc_17.txt...","[entertainment, gaming]"
38,What categories does this paper split the RAG ...,1,0.557974,{'doc_19.txt': 5},{'doc_19.txt': []},[data_science]
39,In what way can including unrelated documents ...,1,0.487420,{'doc_19.txt': 5},{'doc_19.txt': []},[data_science]

## Retrieve and Generate AI Responses using RAG

In [7]:
# Set up some parameters
aws_profile = "ns-admin"
aws_region = 'us-east-2'
kb_id = "DBSECKYXJV"

# Set up retriever object
rag_analyzer = BedrockKBRetriever(aws_profile=aws_profile,
                                   aws_region=aws_region,
                                   kb_id=kb_id)

# Set queries
queries = df_spqs["question"].tolist()

# Retrieve RAG responses for text related to queries without filtering
rag_analyzer.retrieve_and_generate_results(queries=queries)

# Search RAG responses for text related to queries with filtering
# rag_analyzer.retrieve_and_generate_results(queries=queries,
#                                            source_types=["gaming"])

In [8]:

rag_analyzer.df_rag_res

,query,rag_answer,rag_citations
0,What do keybullet kin drop?,"Keybullet Kin drop a key upon death. However, ...","[s3://ashoka-search-tests/doc_0.txt, s3://asho..."
1,What kind of gun does the bandana bullet kin use?,The Bandana Bullet Kin wields a Machine Pistol.,[s3://ashoka-search-tests/doc_0.txt]
2,What do the giants look like?,The search results do not provide a descriptio...,"[s3://ashoka-search-tests/doc_15.txt, s3://ash..."
3,What happens on day 2?,"Sorry, I am unable to assist you with this req...",[]
4,What were the requirements for the project?,"The requirements for the project, which was to...",[s3://ashoka-search-tests/doc_2.txt]
5,What data did was used to test the prototype?,The prototype was tested using Wikipedia pages...,[s3://ashoka-search-tests/doc_2.txt]
6,How do the data storage options compare?,The data storage options include several combi...,[s3://ashoka-search-tests/doc_3.txt]
7,When was UTF-8 support added for European lang...,UTF-8 encoding for European languages was adde...,[s3://ashoka-search-tests/doc_3.txt]
8,How do I make a button?,"To create a button, you can use the `mo.ui.but...","[s3://ashoka-search-tests/doc_4.txt, s3://asho..."
9,When might I use caching?,You might use caching when you have expensive ...,"[s3://ashoka-search-tests/doc_4.txt, s3://asho..."
10,What are the key topics of this article?,"Sorry, I am unable to assist you with this req...",[]
11,Do I have to do something all by myself to be ...,"Sorry, I am unable to assist you with this req...",[]
12,What kinds of models would need to be official...,General-purpose AI models that were trained us...,"[s3://ashoka-search-tests/doc_6.txt, s3://asho..."
13,"What kinds of AI carry ""systematic risks""?",General-purpose AI models that are very capabl...,"[s3://ashoka-search-tests/doc_6.txt, s3://asho..."
14,Which quest does the emperor give the player?,"Sorry, I am unable to assist you with this req...",[]
15,Who ambushes the party at Wyrm's lookout?,The party is ambushed by a group of Gish'ra wa...,[s3://ashoka-search-tests/doc_7.txt]
16,What did I drink at the pintxo bars?,"You drank txakoli, a lightly effervescent whit...","[s3://ashoka-search-tests/doc_8.txt, s3://asho..."
17,Which part of the trip did I like the most?,"Sorry, I am unable to assist you with this req...",[]
18,What is the meaning behind the infrared scenes?,"Sorry, I am unable to assist you with this req...",[]
19,How do the people who commit atrocious acts an...,The search results do not provide a direct com...,"[s3://ashoka-search-tests/doc_9.txt, s3://asho..."
20,What is the policy on Tai Chi?,The Loony Party would make all MPs have half a...,"[s3://ashoka-search-tests/doc_10.txt, s3://ash..."
21,What is the proposed change for the British mu...,The proposed change for the British Museum is ...,"[s3://ashoka-search-tests/doc_10.txt, s3://ash..."
22,How much faster is the Tesla A100 compared to ...,"Sorry, I am unable to assist you with this req...",[]
23,For what work did I receive criticism for my r...,"Sorry, I am unable to assist you with this req...",[]
24,How does function exporting differ between Gle...,"In Gleam, functions are private by default and...",[s3://ashoka-search-tests/doc_12.txt]
25,What is the syntax for pipe,"The syntax for pipe in Gleam is ""|>"".",[s3://ashoka-search-tests/doc_12.txt]
26,Why are the top-right values in the raw attent...,"Sorry, I am unable to assist you with this req...",[]
27,How can I freeze a variable during training in...,"Sorry, I am unable to assist you with this req...",[]
28,How is the narrator related to Perry,"Sorry, I am unable to assist you with this req...",[]
29,How long has the narrator been sober for?,"Sorry, I am unable to assist you with this req...",[]
30,What is the name of the space station?,The space station is called Babystation Beta.,[s3://ashoka-search-tests/doc_15.txt]
31,What languages do the people of Pacifico del R...,The people of Pacifico del Rio speak one langu...,[s3://ashoka-search-tests/doc_15.txt]
32,In which patch was pet adoption added?,"Sorry, I am unable to assist you with this req...",[]
33,When did mushroom trees stop dropping wood?,"Sorry, I am unable to assist you with this req...",[]
34,Where was Alan Wake 2 officially announced?,"Sorry, I am unable to assist you with this req...",[]
35,When is this game set?,"Sorry, I am unable to assist you with this req...",[]
36,Who wrote 'Divine Rivals'?,"Sorry, I am unable to assist you with this req...",[]
37,Who was resurrected with a group of other murd...,Lou was resurrected with a group of other wome...,"[s3://ashoka-search-tests/doc_18.txt, s3://ash..."
38,What categories does this paper split the RAG ...,"Sorry, I am unable to assist you with this req...",[]
39,In what way can including unrelated documents ...,"Sorry, I am unable to assist you with this req...",[]

In [9]:
df_rag_res_ans = rag_analyzer.df_rag_res.copy(deep=True)

df_rag_res_ans["answer"] = ""
for idx in df_rag_res_ans.index:
    if df_rag_res_ans.loc[idx, "query"] == df_spqs.loc[idx, "question"]:
        df_rag_res_ans.loc[idx, "answer"] = df_spqs.loc[idx, "answer"]
    else:
        print("query problem: {}".format(idx))

# df_spqs
df_rag_res_ans

,query,rag_answer,rag_citations,answer
0,What do keybullet kin drop?,"Keybullet Kin drop a key upon death. However, ...","[s3://ashoka-search-tests/doc_0.txt, s3://asho...",Keybullet kin drop a key upon death.
1,What kind of gun does the bandana bullet kin use?,The Bandana Bullet Kin wields a Machine Pistol.,[s3://ashoka-search-tests/doc_0.txt],The bandana bullet kin wields a machine pistol.
2,What do the giants look like?,The search results do not provide a descriptio...,"[s3://ashoka-search-tests/doc_15.txt, s3://ash...","One giant is burly, grey-skinned, and 20 feet ..."
3,What happens on day 2?,"Sorry, I am unable to assist you with this req...",[],"After a few miles of winding tunnel, you emerg..."
4,What were the requirements for the project?,"The requirements for the project, which was to...",[s3://ashoka-search-tests/doc_2.txt],The tool had the following requirements:\n- Ch...
5,What data did was used to test the prototype?,The prototype was tested using Wikipedia pages...,[s3://ashoka-search-tests/doc_2.txt],Grace Hopper's Wikipedia page and Alan Turing'...
6,How do the data storage options compare?,The data storage options include several combi...,[s3://ashoka-search-tests/doc_3.txt],For fast start: use SQLite3 and ChromaDB (File...
7,When was UTF-8 support added for European lang...,UTF-8 encoding for European languages was adde...,[s3://ashoka-search-tests/doc_3.txt],UTF-8 support was added for European languages...
8,How do I make a button?,"To create a button, you can use the `mo.ui.but...","[s3://ashoka-search-tests/doc_4.txt, s3://asho...",import marimo as mo\n\nbutton = mo.ui.run_butt...
9,When might I use caching?,You might use caching when you have expensive ...,"[s3://ashoka-search-tests/doc_4.txt, s3://asho...","You might use caching when, for example, your ..."
10,What are the key topics of this article?,"Sorry, I am unable to assist you with this req...",[],"The key topics of this article are: ""why prior..."
11,Do I have to do something all by myself to be ...,"Sorry, I am unable to assist you with this req...",[],You don’t have to be solely responsible for so...
12,What kinds of models would need to be official...,General-purpose AI models that were trained us...,"[s3://ashoka-search-tests/doc_6.txt, s3://asho...",High-risk AI systems that are deployed by publ...
13,"What kinds of AI carry ""systematic risks""?",General-purpose AI models that are very capabl...,"[s3://ashoka-search-tests/doc_6.txt, s3://asho...","For now, general purpose AI models that were t..."
14,Which quest does the emperor give the player?,"Sorry, I am unable to assist you with this req...",[],"The emperor gives the player the ""Visit the Em..."
15,Who ambushes the party at Wyrm's lookout?,The party is ambushed by a group of Gish'ra wa...,[s3://ashoka-search-tests/doc_7.txt],"On the way to Baldur's Gate, the party will be..."
16,What did I drink at the pintxo bars?,"You drank txakoli, a lightly effervescent whit...","[s3://ashoka-search-tests/doc_8.txt, s3://asho...",You drank txakoli at the pintxo bars.
17,Which part of the trip did I like the most?,"Sorry, I am unable to assist you with this req...",[],Your favourite part of the trip was your four ...
18,What is the meaning behind the infrared scenes?,"Sorry, I am unable to assist you with this req...",[],The significance of the use of infrared might ...
19,How do the people who commit atrocious acts an...,The search results do not provide a direct com...,"[s3://ashoka-search-tests/doc_9.txt, s3://asho...",The Zone of Interest does not really different...
20,What is the policy on Tai Chi?,The Loony Party would make all MPs have half a...,"[s3://ashoka-search-tests/doc_10.txt, s3://ash...",In order to calm down the passions and stresse...
21,What is the proposed change for the British mu...,The proposed change for the British Museum is ...,"[s3://ashoka-search-tests/doc_10.txt, s3://ash...",The British Museum should have a Daddy’s secti...
22,How much faster is the Tesla A100 compared to ...,"Sorry, I am unable to assist you with this req...",[],When measured on the SE-ResNeXt101 deep learni...
23,For what work did I receive criticism for my r...,"Sorry, I am unable to assist you with this req...",[],You received criticism for your research on sp...
24,How does function exporting differ between Gle...,"In Gleam, functions are private by default and...",[s3://ashoka-search-tests/doc_12.txt],"In Python, top level functions are exported by..."
25,What is the syntax for pipe,"The syntax for pipe in Gleam is ""|>"".",[s3://ashoka-search-tests/doc_12.txt],The operator for Pipe in Gleam is '|>'.
26,Why are the top-right values in the raw attent...,"Sorry, I am unable to assist you with this req...",[],A mask of negative infinity is applied to the ...
27,How can I freeze a variable during training in...,"Sorry, I am unable to assist you with this req...",[],"To freeze an attribute during training, you ca..."
28,How is the narrator related to Perry,"Sorry, I am unable to assist you with this req...",[],Perry is the narrator's brother.
29,How long has the narrator been sober for?,"Sorry, I am unable to assist you with this req...",[],The author had been sober for seven hundred an...
30,What is the name of the space station?,The space station is called Babystation Beta.,[s3://ashoka-search-tests/doc_15.txt],"The space station is called ""Babystation Beta""."
31,What languages do the people of Pacifico del R...,The people of Pacifico del Rio speak one langu...,[s3://ashoka-search-tests/doc_15.txt],All of the humans speak a single language that...
32,In which patch was pet adoption added?,"Sorry, I am unable to assist you with this req...",[],The ability to adopt pets from Marnie's shop f...
33,When did mushroom trees stop dropping wood?,"Sorry, I am unable to assist you with this req...",[],Mushroom trees stopped dropping wood in patch ...
34,Where was Alan Wake 2 officially announced?,"Sorry, I am unable to assist you with this req...",[],Alan Wake 2 was officially announced at The Ga...
35,When is this game set?,"Sorry, I am unable to assist you with this req...",[],"This game is set in 2023, thirteen years after..."
36,Who wrote 'Divine Rivals'?,"Sorry, I am unable to assist you with this req...",[],Rebecca Ross wrote 'Divine Rivals'.
37,Who was resurrected with a group of other murd...,Lou was resurrected with a group of other wome...,"[s3://ashoka-search-tests/doc_18.txt, s3://ash...",Lou was resurrected along with a handful of ot...
38,What categories does this paper split the RAG ...,"Sorry, I am unable to assist you with this req...",[],This paper organizes the RAG paradigm into fou...
39,In what way can including unrelated documents ...,"Sorry, I am unable to assist you with this req...",[],"Noise Power (Cuconasu et al., 2024) provide a ..."